<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\CodeHive.Shared\CodeHive.Shared.csproj" />
    <ProjectReference Include="..\..\CodeHive.Infrastructure\CodeHive.Infrastructure.csproj" />
    <ProjectReference Include="..\CodeHive.Posts\CodeHive.Posts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

</Project>
